services:
  nats:
    image: nats:2.10.24
    ports:
      - '4222:4222'
      - '8222:8222'
    volumes:
      - ./nats.conf:/nats.conf
    command:
      - '-c'
      - '/nats.conf'
    container_name: nats-test
    restart: always
